# Generated by Django 4.0.5 on 2022-06-04 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of team')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='task name')),
                ('status', models.CharField(max_length=50, verbose_name='task status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='when this project started')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='when it was completed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.team')),
            ],
        ),
    ]
